"""
Django settings for AgroData project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+3$=4#zfr_u1-9jgpxrt(!au5%oo=lifi9ak(q*6x38-8t5+cm'


# ------------------------------------------------------------------
# AMBIENTE: CONFIGURAÇÕES DE PRODUÇÃO
# ------------------------------------------------------------------

# 1. DEBUG: Deve ser False em produção.
#    DEBUG = True  # <-- Configuração de Desenvolvimento
DEBUG = True    # <-- Configuração de Produção

# 2. ALLOWED_HOSTS: Deve listar os domínios em produção.
#    ALLOWED_HOSTS = []  # <-- Configuração de Desenvolvimento
ALLOWED_HOSTS = ['codando.site', 'www.codando.site']  # <-- Configuração de Produção


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # <-- Linha adicionada para habilitar o filtro 'intcomma'
    'home',
    'agro_app',
    'fichatecnica_app',
    'climalocal_app',
    'info_app',
    'terreno_app',
    'planodeplantio_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AgroData.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AgroData.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'agrodata_db',
        'USER': 'agrodata_user',
        'PASSWORD': 'Gsp@univesp2025',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# 3. STATIC_ROOT: É OBRIGATÓRIO em Produção, usado pelo 'collectstatic'
#    Em produção, o Apache serve arquivos estáticos diretamente deste diretório.
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# 4. STATICFILES_DIRS: Usado SOMENTE no modo de desenvolvimento (DEBUG=True)
#    Em produção, deve ser comentado ou removido, pois STATIC_ROOT é usado.
STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, 'static')  # <-- Configuração de Desenvolvimento (DESATIVADO em Produção)
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# ------------------------------------------------------------------
# CORREÇÃO DE ENCODING CRÍTICA PARA WSGI
# ------------------------------------------------------------------

# Garante que o Django use UTF-8 para codificação de requisições e arquivos,
# o que complementa a correção que será feita no Apache/WSGI.
DEFAULT_CHARSET = 'utf-8'
FILE_CHARSET = 'utf-8'