# Generated by Django 5.2.6 on 2025-10-11 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto Agrícola',
                'verbose_name_plural': 'Produtos Agrícolas',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobrenome')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cultivo_principal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cultivo Principal')),
                ('contact', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato (Telefone/WhatsApp)')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (ID IBGE)')),
                ('cidade', models.CharField(blank=True, max_length=7, null=True, verbose_name='Município (ID IBGE)')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Terreno')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Área')),
                ('unidade_area', models.CharField(max_length=20, verbose_name='Unidade de Medida')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (ID IBGE)')),
                ('cidade', models.CharField(blank=True, max_length=7, null=True, verbose_name='Município (ID IBGE)')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrenos', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Terreno',
                'verbose_name_plural': 'Terrenos',
            },
        ),
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_ibge', models.CharField(max_length=2, verbose_name='Estado IBGE')),
                ('cidade_ibge', models.CharField(max_length=7, verbose_name='Município IBGE')),
                ('data_hora', models.DateTimeField(verbose_name='Data/Hora da Previsão')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura (°C)')),
                ('precipitacao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precipitação (mm)')),
                ('terreno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dados_climaticos', to='agro_app.terreno')),
            ],
            options={
                'verbose_name': 'Dado Climático',
                'verbose_name_plural': 'Dados Climáticos',
            },
        ),
        migrations.CreateModel(
            name='PlanoPlantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_colheita_prevista', models.DateField(blank=True, null=True, verbose_name='Colheita Prevista')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro_app.produto', verbose_name='Produto Plantado')),
                ('terreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantios', to='agro_app.terreno', verbose_name='Terreno')),
            ],
            options={
                'verbose_name': 'Plantio',
                'verbose_name_plural': 'Plantios',
                'unique_together': {('terreno', 'produto', 'data_inicio')},
            },
        ),
    ]
