# Generated by Django 5.2.6 on 2025-10-16 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto Agrícola',
                'verbose_name_plural': 'Produtos Agrícolas',
            },
        ),
        migrations.CreateModel(
            name='PlanoPlantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Novo Plano', max_length=100, verbose_name='Nome do Plano')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_colheita_prevista', models.DateField(blank=True, null=True, verbose_name='Colheita Prevista')),
                ('status', models.CharField(choices=[('ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('RASCUNHO', 'Rascunho')], default='RASCUNHO', max_length=20)),
                ('rendimento_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidade_rendimento', models.CharField(choices=[('KG', 'Quilograma (kg)'), ('TON', 'Tonelada (ton)'), ('L', 'Litro (L)'), ('SAC', 'Saca (Sac)'), ('UN', 'Unidade')], default='KG', max_length=10)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_proprietario', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário do Plano')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro_app.produto', verbose_name='Produto Plantado')),
            ],
            options={
                'verbose_name': 'Plano de Plantio',
                'verbose_name_plural': 'Planos de Plantio',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EtapaPlantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREPARO', 'Preparo do Solo'), ('PLANTIO', 'Plantio'), ('MANUTENCAO', 'Manutenção/Tratos Culturais'), ('COLHEITA', 'Colheita'), ('OUTRA', 'Outra Etapa')], max_length=20)),
                ('nome', models.CharField(help_text='Nome curto da tarefa', max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_prevista', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('insumo_usado', models.CharField(blank=True, help_text='Ex: Fertilizante NPK 10-10-10', max_length=100, null=True)),
                ('quantidade_insumo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidade_insumo', models.CharField(blank=True, choices=[('KG', 'Quilograma (kg)'), ('TON', 'Tonelada (ton)'), ('L', 'Litro (L)'), ('SAC', 'Saca (Sac)'), ('UN', 'Unidade')], max_length=10, null=True)),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='agro_app.planoplantio')),
            ],
            options={
                'verbose_name': 'Etapa de Plantio',
                'verbose_name_plural': 'Etapas de Plantio',
                'ordering': ['data_prevista'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobrenome')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cultivo_principal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cultivo Principal')),
                ('contact', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato (Telefone/WhatsApp)')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (ID IBGE)')),
                ('cidade', models.CharField(blank=True, max_length=7, null=True, verbose_name='Município (ID IBGE)')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Terreno')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Área')),
                ('unidade_area', models.CharField(max_length=20, verbose_name='Unidade de Medida')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (ID IBGE)')),
                ('cidade', models.CharField(blank=True, max_length=7, null=True, verbose_name='Município (ID IBGE)')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrenos', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Terreno',
                'verbose_name_plural': 'Terrenos',
            },
        ),
        migrations.AddField(
            model_name='planoplantio',
            name='terreno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantios', to='agro_app.terreno', verbose_name='Terreno'),
        ),
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_ibge', models.CharField(max_length=2, verbose_name='Estado IBGE')),
                ('cidade_ibge', models.CharField(max_length=7, verbose_name='Município IBGE')),
                ('data_hora', models.DateTimeField(verbose_name='Data/Hora da Previsão')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura (°C)')),
                ('precipitacao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precipitação (mm)')),
                ('terreno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dados_climaticos', to='agro_app.terreno')),
            ],
            options={
                'verbose_name': 'Dado Climático',
                'verbose_name_plural': 'Dados Climáticos',
            },
        ),
    ]
