# Generated by Django 5.2.6 on 2025-09-13 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoPlantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plantacao', models.CharField(max_length=200)),
                ('cultura', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=200)),
                ('area', models.DecimalField(decimal_places=2, help_text='Área em hectares', max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DadosSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('temperatura_solo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umidade_solo', models.IntegerField(help_text='Umidade do solo em %')),
                ('plano_plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro_app.planoplantio')),
            ],
        ),
        migrations.CreateModel(
            name='DadosClimaticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umidade_ar', models.IntegerField(help_text='Umidade do ar em %')),
                ('pressao_atmosferica', models.IntegerField(help_text='Pressão em hPa')),
                ('velocidade_vento', models.DecimalField(decimal_places=2, help_text='Velocidade em m/s', max_digits=5)),
                ('descricao_clima', models.CharField(max_length=100)),
                ('plano_plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro_app.planoplantio')),
            ],
        ),
    ]
