# Generated by Django 5.2.6 on 2025-10-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
    ]
