# Generated by Django 5.2.6 on 2025-10-11 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0002_profile_pais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planoplantio',
            options={'ordering': ['data_inicio'], 'verbose_name': 'Plano de Plantio', 'verbose_name_plural': 'Planos de Plantio'},
        ),
        migrations.AlterUniqueTogether(
            name='planoplantio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='planoplantio',
            name='nome',
            field=models.CharField(default='Novo Plano', max_length=100, verbose_name='Nome do Plano'),
        ),
        migrations.AddField(
            model_name='planoplantio',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planos_proprietario', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário do Plano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planoplantio',
            name='rendimento_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='planoplantio',
            name='status',
            field=models.CharField(choices=[('ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('RASCUNHO', 'Rascunho')], default='RASCUNHO', max_length=20),
        ),
        migrations.AddField(
            model_name='planoplantio',
            name='unidade_rendimento',
            field=models.CharField(choices=[('KG', 'Quilograma (kg)'), ('TON', 'Tonelada (ton)'), ('L', 'Litro (L)'), ('SAC', 'Saca (Sac)'), ('UN', 'Unidade')], default='KG', max_length=10),
        ),
        migrations.AlterField(
            model_name='planoplantio',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro_app.produto', verbose_name='Produto Plantado'),
        ),
        migrations.CreateModel(
            name='EtapaPlantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREPARO', 'Preparo do Solo'), ('PLANTIO', 'Plantio'), ('MANUTENCAO', 'Manutenção/Tratos Culturais'), ('COLHEITA', 'Colheita'), ('OUTRA', 'Outra Etapa')], max_length=20)),
                ('nome', models.CharField(help_text='Nome curto da tarefa', max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_prevista', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('insumo_usado', models.CharField(blank=True, help_text='Ex: Fertilizante NPK 10-10-10', max_length=100, null=True)),
                ('quantidade_insumo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidade_insumo', models.CharField(blank=True, choices=[('KG', 'Quilograma (kg)'), ('TON', 'Tonelada (ton)'), ('L', 'Litro (L)'), ('SAC', 'Saca (Sac)'), ('UN', 'Unidade')], max_length=10, null=True)),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='agro_app.planoplantio')),
            ],
            options={
                'verbose_name': 'Etapa de Plantio',
                'verbose_name_plural': 'Etapas de Plantio',
                'ordering': ['data_prevista'],
            },
        ),
    ]
