# Generated by Django 5.2.6 on 2025-09-27 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0003_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade (IBGE ID ou Nome)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cultivo_principal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cultivo Principal (Nome Normalizado)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado (IBGE ID ou Nome)'),
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Terreno')),
                ('size', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tamanho')),
                ('unit', models.CharField(choices=[('HA', 'Hectare (ha)'), ('M2', 'Metros Quadrados (m²)')], default='HA', max_length=2, verbose_name='Unidade de Medida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrenos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terreno',
                'verbose_name_plural': 'Terrenos',
                'ordering': ['name'],
            },
        ),
    ]
