# Generated by Django 5.2.6 on 2025-09-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0004_alter_profile_city_alter_profile_cultivo_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terreno',
            name='size',
        ),
        migrations.AddField(
            model_name='terreno',
            name='area',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Área'),
            preserve_default=False,
        ),
    ]
