# Generated by Django 5.2.6 on 2025-10-02 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0005_remove_terreno_size_terreno_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planoplantio',
            options={'verbose_name': 'Plano de Cultivo', 'verbose_name_plural': 'Planos de Cultivo'},
        ),
        migrations.AddField(
            model_name='planoplantio',
            name='terreno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agro_app.terreno', verbose_name='Terreno Selecionado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planoplantio',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Área em hectares', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planoplantio',
            name='cultura',
            field=models.CharField(max_length=100, verbose_name='Cultura Escolhida (Nome Normalizado do Produto)'),
        ),
        migrations.AlterField(
            model_name='planoplantio',
            name='localizacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Localização (Cidade/Estado)'),
        ),
        migrations.AlterField(
            model_name='planoplantio',
            name='nome_plantacao',
            field=models.CharField(max_length=200, verbose_name='Nome do Plano'),
        ),
    ]
