# Generated by Django 5.2.6 on 2025-10-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0006_alter_planoplantio_options_planoplantio_terreno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoplantio',
            name='ficha_tecnica',
            field=models.JSONField(default=dict, verbose_name='Ficha Técnica Consolidada'),
        ),
    ]
